//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agenda03.RefServAgenda {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="DCListaPersonas", Namespace="http://agenda.datacontracts", ItemName="Persona")]
    [System.SerializableAttribute()]
    public class DCListaPersonas : System.Collections.Generic.List<Agenda03.RefServAgenda.Persona> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://agenda.datacontracts")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoField;
        
        private string NombreField;
        
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        private Agenda03.RefServAgenda.DCListaTelefono TelefonosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public Agenda03.RefServAgenda.DCListaTelefono Telefonos {
            get {
                return this.TelefonosField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonosField, value) != true)) {
                    this.TelefonosField = value;
                    this.RaisePropertyChanged("Telefonos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="DCListaTelefono", Namespace="http://agenda.datacontracts", ItemName="Telefono")]
    [System.SerializableAttribute()]
    public class DCListaTelefono : System.Collections.Generic.List<Agenda03.RefServAgenda.Telefono> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Telefono", Namespace="http://agenda.datacontracts")]
    [System.SerializableAttribute()]
    public partial class Telefono : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoTelefonoField;
        
        private string NroTelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodigoTelefono {
            get {
                return this.CodigoTelefonoField;
            }
            set {
                if ((this.CodigoTelefonoField.Equals(value) != true)) {
                    this.CodigoTelefonoField = value;
                    this.RaisePropertyChanged("CodigoTelefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string NroTelefono {
            get {
                return this.NroTelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.NroTelefonoField, value) != true)) {
                    this.NroTelefonoField = value;
                    this.RaisePropertyChanged("NroTelefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://agenda.modelo.ServiceContracts", ConfigurationName="RefServAgenda.SCAgenda")]
    public interface SCAgenda {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación ObtenerPersonas no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="ObtenerPersonas", ReplyAction="http://agenda.modelo.ServiceContracts/SCAgenda/ObtenerPersonasResponse")]
        Agenda03.RefServAgenda.MCListaPersonas ObtenerPersonas(Agenda03.RefServAgenda.ObtenerPersonasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ObtenerPersonas", ReplyAction="http://agenda.modelo.ServiceContracts/SCAgenda/ObtenerPersonasResponse")]
        System.Threading.Tasks.Task<Agenda03.RefServAgenda.MCListaPersonas> ObtenerPersonasAsync(Agenda03.RefServAgenda.ObtenerPersonasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación SeleccionaPersona no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="SeleccionaPersona", ReplyAction="http://agenda.modelo.ServiceContracts/SCAgenda/SeleccionaPersonaResponse")]
        Agenda03.RefServAgenda.MCPersona SeleccionaPersona(Agenda03.RefServAgenda.MCCodigo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="SeleccionaPersona", ReplyAction="http://agenda.modelo.ServiceContracts/SCAgenda/SeleccionaPersonaResponse")]
        System.Threading.Tasks.Task<Agenda03.RefServAgenda.MCPersona> SeleccionaPersonaAsync(Agenda03.RefServAgenda.MCCodigo request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación InsertaPersona no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="InsertaPersona", ReplyAction="http://agenda.modelo.ServiceContracts/SCAgenda/InsertaPersonaResponse")]
        Agenda03.RefServAgenda.MCRespuesta InsertaPersona(Agenda03.RefServAgenda.MCPersona request);
        
        [System.ServiceModel.OperationContractAttribute(Action="InsertaPersona", ReplyAction="http://agenda.modelo.ServiceContracts/SCAgenda/InsertaPersonaResponse")]
        System.Threading.Tasks.Task<Agenda03.RefServAgenda.MCRespuesta> InsertaPersonaAsync(Agenda03.RefServAgenda.MCPersona request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación ActualizaPersona no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="ActualizaPersona", ReplyAction="http://agenda.modelo.ServiceContracts/SCAgenda/ActualizaPersonaResponse")]
        Agenda03.RefServAgenda.MCRespuesta ActualizaPersona(Agenda03.RefServAgenda.MCPersona request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ActualizaPersona", ReplyAction="http://agenda.modelo.ServiceContracts/SCAgenda/ActualizaPersonaResponse")]
        System.Threading.Tasks.Task<Agenda03.RefServAgenda.MCRespuesta> ActualizaPersonaAsync(Agenda03.RefServAgenda.MCPersona request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación EliminaPersona no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="EliminaPersona", ReplyAction="http://agenda.modelo.ServiceContracts/SCAgenda/EliminaPersonaResponse")]
        Agenda03.RefServAgenda.MCRespuesta EliminaPersona(Agenda03.RefServAgenda.MCCodigo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="EliminaPersona", ReplyAction="http://agenda.modelo.ServiceContracts/SCAgenda/EliminaPersonaResponse")]
        System.Threading.Tasks.Task<Agenda03.RefServAgenda.MCRespuesta> EliminaPersonaAsync(Agenda03.RefServAgenda.MCCodigo request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerPersonasRequest {
        
        public ObtenerPersonasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MCListaPersonas {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://agenda.modelo.ServiceContracts", Order=0)]
        public Agenda03.RefServAgenda.DCListaPersonas Personas;
        
        public MCListaPersonas() {
        }
        
        public MCListaPersonas(Agenda03.RefServAgenda.DCListaPersonas Personas) {
            this.Personas = Personas;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MCCodigo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://agenda.modelo.ServiceContracts", Order=0)]
        public int CodigoPersona;
        
        public MCCodigo() {
        }
        
        public MCCodigo(int CodigoPersona) {
            this.CodigoPersona = CodigoPersona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MCPersona {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://agenda.modelo.ServiceContracts", Order=0)]
        public Agenda03.RefServAgenda.Persona DatosPersona;
        
        public MCPersona() {
        }
        
        public MCPersona(Agenda03.RefServAgenda.Persona DatosPersona) {
            this.DatosPersona = DatosPersona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MCRespuesta {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://agenda.modelo.ServiceContracts", Order=0)]
        public bool Respuesta;
        
        public MCRespuesta() {
        }
        
        public MCRespuesta(bool Respuesta) {
            this.Respuesta = Respuesta;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SCAgendaChannel : Agenda03.RefServAgenda.SCAgenda, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SCAgendaClient : System.ServiceModel.ClientBase<Agenda03.RefServAgenda.SCAgenda>, Agenda03.RefServAgenda.SCAgenda {
        
        public SCAgendaClient() {
        }
        
        public SCAgendaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SCAgendaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SCAgendaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SCAgendaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agenda03.RefServAgenda.MCListaPersonas Agenda03.RefServAgenda.SCAgenda.ObtenerPersonas(Agenda03.RefServAgenda.ObtenerPersonasRequest request) {
            return base.Channel.ObtenerPersonas(request);
        }
        
        public Agenda03.RefServAgenda.DCListaPersonas ObtenerPersonas() {
            Agenda03.RefServAgenda.ObtenerPersonasRequest inValue = new Agenda03.RefServAgenda.ObtenerPersonasRequest();
            Agenda03.RefServAgenda.MCListaPersonas retVal = ((Agenda03.RefServAgenda.SCAgenda)(this)).ObtenerPersonas(inValue);
            return retVal.Personas;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agenda03.RefServAgenda.MCListaPersonas> Agenda03.RefServAgenda.SCAgenda.ObtenerPersonasAsync(Agenda03.RefServAgenda.ObtenerPersonasRequest request) {
            return base.Channel.ObtenerPersonasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agenda03.RefServAgenda.MCListaPersonas> ObtenerPersonasAsync() {
            Agenda03.RefServAgenda.ObtenerPersonasRequest inValue = new Agenda03.RefServAgenda.ObtenerPersonasRequest();
            return ((Agenda03.RefServAgenda.SCAgenda)(this)).ObtenerPersonasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agenda03.RefServAgenda.MCPersona Agenda03.RefServAgenda.SCAgenda.SeleccionaPersona(Agenda03.RefServAgenda.MCCodigo request) {
            return base.Channel.SeleccionaPersona(request);
        }
        
        public Agenda03.RefServAgenda.Persona SeleccionaPersona(int CodigoPersona) {
            Agenda03.RefServAgenda.MCCodigo inValue = new Agenda03.RefServAgenda.MCCodigo();
            inValue.CodigoPersona = CodigoPersona;
            Agenda03.RefServAgenda.MCPersona retVal = ((Agenda03.RefServAgenda.SCAgenda)(this)).SeleccionaPersona(inValue);
            return retVal.DatosPersona;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agenda03.RefServAgenda.MCPersona> Agenda03.RefServAgenda.SCAgenda.SeleccionaPersonaAsync(Agenda03.RefServAgenda.MCCodigo request) {
            return base.Channel.SeleccionaPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agenda03.RefServAgenda.MCPersona> SeleccionaPersonaAsync(int CodigoPersona) {
            Agenda03.RefServAgenda.MCCodigo inValue = new Agenda03.RefServAgenda.MCCodigo();
            inValue.CodigoPersona = CodigoPersona;
            return ((Agenda03.RefServAgenda.SCAgenda)(this)).SeleccionaPersonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agenda03.RefServAgenda.MCRespuesta Agenda03.RefServAgenda.SCAgenda.InsertaPersona(Agenda03.RefServAgenda.MCPersona request) {
            return base.Channel.InsertaPersona(request);
        }
        
        public bool InsertaPersona(Agenda03.RefServAgenda.Persona DatosPersona) {
            Agenda03.RefServAgenda.MCPersona inValue = new Agenda03.RefServAgenda.MCPersona();
            inValue.DatosPersona = DatosPersona;
            Agenda03.RefServAgenda.MCRespuesta retVal = ((Agenda03.RefServAgenda.SCAgenda)(this)).InsertaPersona(inValue);
            return retVal.Respuesta;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agenda03.RefServAgenda.MCRespuesta> Agenda03.RefServAgenda.SCAgenda.InsertaPersonaAsync(Agenda03.RefServAgenda.MCPersona request) {
            return base.Channel.InsertaPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agenda03.RefServAgenda.MCRespuesta> InsertaPersonaAsync(Agenda03.RefServAgenda.Persona DatosPersona) {
            Agenda03.RefServAgenda.MCPersona inValue = new Agenda03.RefServAgenda.MCPersona();
            inValue.DatosPersona = DatosPersona;
            return ((Agenda03.RefServAgenda.SCAgenda)(this)).InsertaPersonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agenda03.RefServAgenda.MCRespuesta Agenda03.RefServAgenda.SCAgenda.ActualizaPersona(Agenda03.RefServAgenda.MCPersona request) {
            return base.Channel.ActualizaPersona(request);
        }
        
        public bool ActualizaPersona(Agenda03.RefServAgenda.Persona DatosPersona) {
            Agenda03.RefServAgenda.MCPersona inValue = new Agenda03.RefServAgenda.MCPersona();
            inValue.DatosPersona = DatosPersona;
            Agenda03.RefServAgenda.MCRespuesta retVal = ((Agenda03.RefServAgenda.SCAgenda)(this)).ActualizaPersona(inValue);
            return retVal.Respuesta;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agenda03.RefServAgenda.MCRespuesta> Agenda03.RefServAgenda.SCAgenda.ActualizaPersonaAsync(Agenda03.RefServAgenda.MCPersona request) {
            return base.Channel.ActualizaPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agenda03.RefServAgenda.MCRespuesta> ActualizaPersonaAsync(Agenda03.RefServAgenda.Persona DatosPersona) {
            Agenda03.RefServAgenda.MCPersona inValue = new Agenda03.RefServAgenda.MCPersona();
            inValue.DatosPersona = DatosPersona;
            return ((Agenda03.RefServAgenda.SCAgenda)(this)).ActualizaPersonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agenda03.RefServAgenda.MCRespuesta Agenda03.RefServAgenda.SCAgenda.EliminaPersona(Agenda03.RefServAgenda.MCCodigo request) {
            return base.Channel.EliminaPersona(request);
        }
        
        public bool EliminaPersona(int CodigoPersona) {
            Agenda03.RefServAgenda.MCCodigo inValue = new Agenda03.RefServAgenda.MCCodigo();
            inValue.CodigoPersona = CodigoPersona;
            Agenda03.RefServAgenda.MCRespuesta retVal = ((Agenda03.RefServAgenda.SCAgenda)(this)).EliminaPersona(inValue);
            return retVal.Respuesta;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agenda03.RefServAgenda.MCRespuesta> Agenda03.RefServAgenda.SCAgenda.EliminaPersonaAsync(Agenda03.RefServAgenda.MCCodigo request) {
            return base.Channel.EliminaPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agenda03.RefServAgenda.MCRespuesta> EliminaPersonaAsync(int CodigoPersona) {
            Agenda03.RefServAgenda.MCCodigo inValue = new Agenda03.RefServAgenda.MCCodigo();
            inValue.CodigoPersona = CodigoPersona;
            return ((Agenda03.RefServAgenda.SCAgenda)(this)).EliminaPersonaAsync(inValue);
        }
    }
}
